kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: registry-dockerhub-config
  labels:
    app: app-name
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZMmh5YVhOelpYSjJaWEpzWlhOek9tZG9jRjltWkdsNFRGRmhlSGRHUmtwamQwRlFNRzlhWWpSTGVXVXlhRTF1Ylhvd1ZVbDVjV009In19fQ==
